### ISSUE TITLE
When querying for 2UTT000000(example), the search API is fired for *

### ISSUE THREAD

**Issue by albingeorge** [unbxd/js-sdk#28]
This seems to be an issue with decoding URL params.

Example:
```
http://search.himalayastore.com/?q=2UTT000000
```
![sdk-issue](https://cloud.githubusercontent.com/assets/1938077/13605315/e7209574-e56c-11e5-9fda-c64892200f6a.png)

In here, the search query is for `2UTT000000`, but the search API is getting fired for `*`.

I debugged a bit and figured out that this happens for those sites which have `noEncoding` set to `false` by default.

In soccercorner, encoding is set, and for this, the correct search API is getting fired:
```
http://soccercorner.unbxdapi.com/?q=2UTT000000
```

To be a bit more specific, the `decode` function is returning the below object:
```
썔M: "4Ӎ4"
```

And because of this, even if the URL(`q=2UTT000000`) is not encoded, the value for `decodedParamscount` returns > 0.
![sdk-issue-decoded](https://cloud.githubusercontent.com/assets/1938077/13605515/e4b81504-e56d-11e5-9f72-2ad1988763b1.png)

**Comment by rahulcs** [comment]
@albingeorge thanks for the detailed issue.

**Comment by rahulcs** [comment]
please set 
```javascript
noEncoding: true
```
while creating the unbxdSearch options

@albingeorge @unbxd/team-solutions
